/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Models.Chamado;
import Models.Cliente;
import Models.Motorista;
import Models.Veiculo;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author henri
 */
public class CriarChamado extends javax.swing.JFrame {

    /**
     * Creates new form Chamado
     */
    public CriarChamado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDadosCliente = new javax.swing.JPanel();
        campoCodigo = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        campoOrigem = new javax.swing.JPanel();
        lblOrigem = new javax.swing.JLabel();
        textOrigem = new javax.swing.JTextField();
        campoDestino = new javax.swing.JPanel();
        lblDestino = new javax.swing.JLabel();
        textDestino = new javax.swing.JTextField();
        campoMotorista = new javax.swing.JPanel();
        lblMotorista = new javax.swing.JLabel();
        textMotorista = new javax.swing.JTextField();
        campoCliente = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        textCliente = new javax.swing.JTextField();
        campoVeiculo = new javax.swing.JPanel();
        lblVeiculo = new javax.swing.JLabel();
        textVeiculo = new javax.swing.JTextField();
        campoValorTotal = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        textValorTotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        campoButtons = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do Chamado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 18))); // NOI18N
        painelDadosCliente.setLayout(new javax.swing.BoxLayout(painelDadosCliente, javax.swing.BoxLayout.Y_AXIS));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodigo.setText("Código:");

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoCodigoLayout = new javax.swing.GroupLayout(campoCodigo);
        campoCodigo.setLayout(campoCodigoLayout);
        campoCodigoLayout.setHorizontalGroup(
            campoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoCodigoLayout.setVerticalGroup(
            campoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoCodigo);

        lblOrigem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrigem.setText("Origem:");

        textOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoOrigemLayout = new javax.swing.GroupLayout(campoOrigem);
        campoOrigem.setLayout(campoOrigemLayout);
        campoOrigemLayout.setHorizontalGroup(
            campoOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoOrigemLayout.setVerticalGroup(
            campoOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoOrigem);

        lblDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDestino.setText("Destino:");

        textDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoDestinoLayout = new javax.swing.GroupLayout(campoDestino);
        campoDestino.setLayout(campoDestinoLayout);
        campoDestinoLayout.setHorizontalGroup(
            campoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoDestinoLayout.setVerticalGroup(
            campoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoDestino);

        lblMotorista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMotorista.setText("Código do Motorista:");

        textMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMotoristaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoMotoristaLayout = new javax.swing.GroupLayout(campoMotorista);
        campoMotorista.setLayout(campoMotoristaLayout);
        campoMotoristaLayout.setHorizontalGroup(
            campoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoMotoristaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoMotoristaLayout.setVerticalGroup(
            campoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoMotorista);

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliente.setText("Código do Cliente:");

        textCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoClienteLayout = new javax.swing.GroupLayout(campoCliente);
        campoCliente.setLayout(campoClienteLayout);
        campoClienteLayout.setHorizontalGroup(
            campoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoClienteLayout.setVerticalGroup(
            campoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoCliente);

        lblVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVeiculo.setText("Placa do Veículo:");

        textVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoVeiculoLayout = new javax.swing.GroupLayout(campoVeiculo);
        campoVeiculo.setLayout(campoVeiculoLayout);
        campoVeiculoLayout.setHorizontalGroup(
            campoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoVeiculoLayout.setVerticalGroup(
            campoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoVeiculo);

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorTotal.setText("Valor total:");

        textValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campoValorTotalLayout = new javax.swing.GroupLayout(campoValorTotal);
        campoValorTotal.setLayout(campoValorTotalLayout);
        campoValorTotalLayout.setHorizontalGroup(
            campoValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        campoValorTotalLayout.setVerticalGroup(
            campoValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDadosCliente.add(campoValorTotal);
        painelDadosCliente.add(jSeparator1);

        campoButtons.setPreferredSize(new java.awt.Dimension(307, 29));
        campoButtons.setLayout(new java.awt.GridLayout(1, 0));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        campoButtons.add(btnCancelar);
        campoButtons.add(filler1);

        btnCriar.setText("Criar Chamado");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        campoButtons.add(btnCriar);

        painelDadosCliente.add(campoButtons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void textDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDestinoActionPerformed

    private void textOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOrigemActionPerformed

    private void textClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if (!textCodigo.getText().equals("") && !textDestino.getText().equals("") && !textMotorista.getText().equals("") && !textOrigem.getText().equals("") && !textCliente.getText().equals("")) {
            HashMap<Integer, Cliente> clientes = lerClientesDoArquivo();
            HashMap<Integer, Motorista> motoristas = lerMotoristasDoArquivo();
            HashMap<String, Veiculo> veiculos = lerVeiculosDoArquivo();
            
            int id = Integer.parseInt(textCodigo.getText());
            String origem = textOrigem.getText();
            String destino = textDestino.getText();
            int idMotorista = Integer.parseInt(textMotorista.getText());
            Motorista motorista = motoristas.get(idMotorista);
            int idCliente = Integer.parseInt(textCliente.getText());
            Cliente cliente = clientes.get(idCliente);
            String placaVeiculo = textVeiculo.getText();
            Veiculo veiculo = veiculos.get(placaVeiculo);
            double valorTotal = Double.parseDouble(textValorTotal.getText());
            LocalDate data = LocalDate.now();

            //Como não foi bem explicado o que é cada atributo ou como tê-los, vou implementar um chmado apenas com os argumentos que entendo
            Chamado chamado = new Chamado(id, data, origem, destino, valorTotal, cliente, motorista, veiculo);
            salvarChamadoNoArquivo(chamado);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Chamado criado com sucesso", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void textMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMotoristaActionPerformed

    private void textVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVeiculoActionPerformed

    private void textValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorTotalActionPerformed

    public HashMap<Integer, Cliente> lerClientesDoArquivo() {
        ArrayList<String> linhas = new ArrayList<>();
        HashMap<Integer, Cliente> clientes = new HashMap<>();
        
        try (BufferedReader reader = new BufferedReader(new FileReader("src/Resources/clientes.txt"))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                linhas.add(linha);
            }

            for (String conteudo : linhas) {
                String[] partes = conteudo.split("\\.");
                int id = Integer.parseInt(partes[0]);
                String rg = partes[1];
                String cpf = partes[2];
                String nome = partes[3];
                String telefone = partes[4];

                Cliente cliente = new Cliente(id, rg, cpf, nome, telefone);
                clientes.put(id, cliente);
            }
        } catch (IOException e) {
            System.out.println("Erro ao ler o arquivo: " + e.getMessage());
        }
        
        return clientes;
    }
    
    public HashMap<Integer, Motorista> lerMotoristasDoArquivo() {
        ArrayList<String> linhas = new ArrayList<>();
        HashMap<Integer, Motorista> motoristas = new HashMap<>();
        
        try (BufferedReader reader = new BufferedReader(new FileReader("src/Resources/motoristas.txt"))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                linhas.add(linha);
            }

            for (String conteudo : linhas) {
                String[] partes = conteudo.split("\\.");
                int id = Integer.parseInt(partes[0]);
                String nome = partes[1];
                String telefone = partes[2];
                String cnh = partes[3];

                Motorista motorista = new Motorista(id, nome, telefone, cnh);
                motoristas.put(id, motorista);
            }
        } catch (IOException e) {
            System.out.println("Erro ao ler o arquivo: " + e.getMessage());
        }
        
        return motoristas;
    }
    
    public HashMap<String, Veiculo> lerVeiculosDoArquivo() {
        ArrayList<String> linhas = new ArrayList<>();
        HashMap<String, Veiculo> veiculos = new HashMap<>();
        
        try (BufferedReader reader = new BufferedReader(new FileReader("src/Resources/veiculos.txt"))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                linhas.add(linha);
            }

            for (String conteudo : linhas) {
                String[] partes = conteudo.split("\\.");
                String placa = partes[0];
                String marca = partes[1];
                String modelo = partes[2];
                String cor = partes[3];
                int ano = Integer.parseInt(partes[4]);

                Veiculo veiculo = new Veiculo(placa, marca, modelo, cor, ano);
                veiculos.put(placa, veiculo);
            }
        } catch (IOException e) {
            System.out.println("Erro ao ler o arquivo: " + e.getMessage());
        }
        
        return veiculos;
    }
    
    public void salvarChamadoNoArquivo(Chamado chamado) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("src/Resources/chamados.txt", true))) {
            writer.write(String.valueOf(chamado.getId()) + '.' + String.valueOf(chamado.getData()) + '.' + chamado.getOrigem() + '.' + chamado.getDestino() + '.' + chamado.getValorTotal() + ".[" + String.valueOf(chamado.getCliente().getId()) + ',' + chamado.getCliente().getNome() + "].[" + String.valueOf(chamado.getMotorista().getId()) + ',' + chamado.getMotorista().getNome() + "].[" + chamado.getVeiculo().getPlaca() + ',' + chamado.getVeiculo().getModelo() + "]\n");
        } catch (IOException e) {
            System.out.println("Erro ao salvar o arquivo: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JPanel campoButtons;
    private javax.swing.JPanel campoCliente;
    private javax.swing.JPanel campoCodigo;
    private javax.swing.JPanel campoDestino;
    private javax.swing.JPanel campoMotorista;
    private javax.swing.JPanel campoOrigem;
    private javax.swing.JPanel campoValorTotal;
    private javax.swing.JPanel campoVeiculo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblMotorista;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JPanel painelDadosCliente;
    private javax.swing.JTextField textCliente;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textDestino;
    private javax.swing.JTextField textMotorista;
    private javax.swing.JTextField textOrigem;
    private javax.swing.JTextField textValorTotal;
    private javax.swing.JTextField textVeiculo;
    // End of variables declaration//GEN-END:variables
}
